version: '3.1'
services:
  api-license-manager:
    image: base-project:latest
    build: .
    restart: always
    ports:
      - "3308:8080"
    environment:
      DB_HOST: 192.168.0.8:5432
      DB_USERNAME: postgres
      DB_PASSWORD: qwe123*
      JWT_SECRET_KEY: 0986430@753776789!1208@948741157
      JWT_EXPIRATION: 86400000
      JWT_ISSUER: base-project-api