api:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      issuer: ${JWT_ISSUER}

upload:
  dir: src/main/resources/files/

server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 60MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    filter: true
    tagsSorter: alpha
    operationsSorter: method
    doc-expansion: none
