package br.com.base.shared.models.enums;

public enum RoleType {
    ROLE_READ_ROLE(Roles.ROLE_READ_ROLE),
    ROLE_CREATE_USER(Roles.ROLE_CREATE_USER),
    ROLE_ADD_USER_GROUPS_ROLES(Roles.ROLE_ADD_USER_GROUPS_ROLES),
    ROLE_REMOVE_USER_GROUPS_ROLES(Roles.ROLE_REMOVE_USER_GROUPS_ROLES),
    ROLE_GET_USER_ROLES(Roles.ROLE_GET_USER_ROLES),
    ROLE_ADD_USER_ROLES(Roles.ROLE_ADD_USER_ROLES),
    ROLE_REMOVE_USER_ROLES(Roles.ROLE_REMOVE_USER_ROLES),
    ROLE_GET_GROUPS_ROLES(Roles.ROLE_GET_GROUPS_ROLES),
    ROLE_GET_GROUP_ROLES_DETAILS(Roles.ROLE_GET_GROUP_ROLES_DETAILS),
    ROLE_CREATE_GROUP_ROLES(Roles.ROLE_CREATE_GROUP_ROLES),
    ROLE_UPDATE_GROUP_ROLES(Roles.ROLE_UPDATE_GROUP_ROLES),
    ROLE_REMOVE_GROUP_ROLES(Roles.ROLE_REMOVE_GROUP_ROLES),
    ROLE_ADD_GROUP_ROLES_ROLES(Roles.ROLE_ADD_GROUP_ROLES_ROLES),
    ROLE_REMOVE_GROUP_ROLES_ROLES(Roles.ROLE_REMOVE_GROUP_ROLES_ROLES),
    ROLE_GET_AVAILABLE_PERMISSIONS(Roles.ROLE_GET_AVAILABLE_PERMISSIONS),
    ROLE_CREATE_LICENSES(Roles.ROLE_CREATE_LICENSES),
    ROLE_GET_LICENSES(Roles.ROLE_GET_LICENSES),
    ROLE_GET_LICENSE_DETAILS(Roles.ROLE_GET_LICENSE_DETAILS),
    ROLE_DOWNLOAD_LICENSE(Roles.ROLE_DOWNLOAD_LICENSE);

    private final String role;

    RoleType(String role) {
        this.role = role;
    }

    public String getRole() {
        return role;
    }

    public interface Roles {
        String ROLE_READ_ROLE = "READ_ROLE";
        String ROLE_CREATE_USER = "ROLE_CREATE_USER";
        String ROLE_ADD_USER_GROUPS_ROLES = "ADD_USER_GROUPS_ROLES";
        String ROLE_REMOVE_USER_GROUPS_ROLES = "REMOVE_USER_GROUPS_ROLES";
        String ROLE_GET_USER_ROLES = "GET_USER_ROLES";
        String ROLE_ADD_USER_ROLES = "ADD_USER_ROLES";
        String ROLE_REMOVE_USER_ROLES = "REMOVE_USER_ROLES";
        String ROLE_GET_GROUPS_ROLES = "GET_GROUPS_ROLES";
        String ROLE_GET_GROUP_ROLES_DETAILS = "GET_GROUP_ROLES_DETAILS";
        String ROLE_CREATE_GROUP_ROLES = "CREATE_GROUP_ROLES";
        String ROLE_UPDATE_GROUP_ROLES = "UPDATE_GROUP_ROLES";
        String ROLE_REMOVE_GROUP_ROLES = "REMOVE_GROUP_ROLES";
        String ROLE_ADD_GROUP_ROLES_ROLES = "ADD_GROUP_ROLES_ROLES";
        String ROLE_REMOVE_GROUP_ROLES_ROLES = "REMOVE_GROUP_ROLES_ROLES";
        String ROLE_GET_AVAILABLE_PERMISSIONS = "ROLE_GET_AVAILABLE_PERMISSIONS";
        String ROLE_CREATE_LICENSES = "ROLE_CREATE_LICENSES";
        String ROLE_GET_LICENSES = "ROLE_GET_LICENSES";
        String ROLE_GET_LICENSE_DETAILS = "ROLE_GET_LICENSE_DETAILS";
        String ROLE_DOWNLOAD_LICENSE = "ROLE_DOWNLOAD_LICENSE";
    }
}
