name: Deploy Presentation Project

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests #Remover ultima parte para executar os tests

      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t olliverzx/postgresql .

      - name: Push Image Docker
        run: docker push olliverzx/postgresql

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image From Docker Hub
        run: docker pull olliverzx/postgresql:latest

      - name: Remove Docker Container
        run: docker rm -f deploy_presentation_actions

      - name: Remover
        run: docker rm -f deploy_presentaion_actions

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 -e DB_URL=${{secrets.DB_URL}} -e DB_USERNAME=${{secrets.DB_USERNAME}} -e DB_PASSWORD='${{secrets.DB_PASSWORD}}' --name deploy_presentation_actions olliverzx/postgresql